### ISSUE TITLE
pressing win+left/right on a maximized window doesn't snap windows properly

### ISSUE THREAD

**Issue by Poopooracoocoo** [microsoft/WinDev#63] opened 2020-11-23 14:51 UTC
## Steps to reproduce

1. open file explorer. (or your browser)
2. maximise
3. win+left

## Expected behavior

window snaps to left side to fill half of the horizontal space 

## Actual behavior

window doesn't fully snap, a bug I've been experiencing since version 1903 to now (version 2009). you need to press win+left again to snap it properly. it makes my workflows just a little bit more annoying and time consuming. 

I don't really like to post into the void aka the feedback hub but you guys seem to have commented on a few of these. I searched for snap. the comment at the top reminds me of a ToS. basically saying that you'll close any issue without explanation. whatevs...

**Comment by Poopooracoocoo** [comment] 2020-11-25 03:42
resizing the snapped window also makes it snap properly. BUT moving and resizing windows is slow and sluggish so it's something I avoid doing.

**Comment by warpdesign** [comment] 2020-11-27 07:47
I can confirm something is wrong. It looks like it's snapping but:
- thumbnails of other windows do not appear on the right (as they would if the window was not maximized when pressing `win + left`)
- the window is slightly off screen at the top

**Comment by Poopooracoocoo** [comment] 2020-11-27 08:17
>the window is slightly off screen at the top

yeah that's what I meant by properly

>thumbnails of other windows do not appear on the right (as they would if the window was not maximized when pressing win + left)

yeah that's because of this bug. note that you need it turned on (it is by default.): 
![image](https://user-images.githubusercontent.com/51363864/100426468-04bbe980-30e5-11eb-923a-aeb7577cfe9f.png)

(just putting this info even though I'm just agreeing, for Rich or anyone else at MS)

**Comment by avarun42** [comment] 2020-12-03 08:49
> yeah that's because of this bug. note that you need it turned on (it is by default.):

If you press Win+Left again the the window thumbnails appear, however. It doesn't seem to be a bug with that setting but just a result of your initial issue.

**Comment by Poopooracoocoo** [comment] 2020-12-04 02:30
>It doesn't seem to be a bug with that setting but just a result of your initial issue.

I know. I just mentioned that for Rich or anyone from MS.

**Comment by AvriMSFT** [comment] 2021-04-13 17:57
Unfortunately, this issue is out of scope for this repo, so it won't be tracked here and will be closed as out of scope. BUT this bug has actually been fixed in the dev channel. So, if you'd like to update to the latest Insider build you will see the fix 🙂.

**Closed as completed by AvriMSFT** 2021-04-13 17:57 UTC
Labels: Resolution-OutOfScope

**Comment by Poopooracoocoo** [comment] 2021-04-14 04:27
Funny how many years it took. @AvriMSFT I thought Rich said that a bunch of annoying bugs were in scope of the repo.

**Comment by riverar** [comment] 2021-04-16 04:37
@Poopooracoocoo He did and that was the wrong approach. The team here is cleaning things up. 👍

**Comment by Poopooracoocoo** [comment] 2021-04-16 05:26
@riverar but the feedback hub is a complete shithole. you have seen it, right? 

what are people like me supposed to do with these stupid annoying bugs that don't get fixed for YEARS? task view, for one, is painful af. the windows explorer leaks get on my nerves.

**Comment by riverar** [comment] 2021-04-16 05:45
@Poopooracoocoo I hear ya. Let's get this one filed under [Desktop Environment] > [Snap and Snap Assist]. Paste a link afterwards and I'll shoot it straight to some shell folks.

**Comment by Poopooracoocoo** [comment] 2021-04-16 07:16
@riverar Bruh. I filed this YEARS ago. This bug has been here since W10 v1903. I ain't doing the dirty work. I'm not finding it for you.

**Comment by riverar** [comment] 2021-04-16 07:23
A talking toilet brush that doesn't want to do any dirty work. Got it.

I found a few items in Feedback Hub though so I'll pass those along right now.

**Comment by Poopooracoocoo** [comment] 2021-04-16 09:06
Ahaha. It's Billie Eyelash :P 

But seriously, I meant that. Filed it years ago. I can't dig through that terrible app that I uninstalled many moons ago. thx for passing it along. i hope you do the same with the other issues in here. i saw that heaps were closed and were likely unfixed and forgotten.
