### ISSUE TITLE
Symbol server PE files are being overwritten with different versions

### ISSUE THREAD

**Issue by randomascii** [microsoft/WinDev#102] opened 2022-01-02 19:46 UTC
### Windows Build Number

Win32NT 10.0.22000.0 Microsoft Windows NT 10.0.22000.0

### Processor Architecture

AMD64

### Memory

16 GB

### Storage Type, free / capacity

SSD 160GB/350GB

### Relevant apps installed

windbg, Chrome

### Traces collected via Feedback Hub

Sorry, no feedback hub traces

### Isssue description

Different versions of kernel32.dll are being published to Microsoft's symbol server with the same timestamp/image-size/filename triplet, with each new version overwriting the previous version. This means that when examining a crash dump from 10.0.22000.376 Windows 11 the results of "lmv m kernel32" will (as of this writing) report that the DLL is both version .318 and version .376. Actually, the exact results depend on the contents of your local symbol server cache and the second number could be .318, .347, or .376, or possibly other numbers.

### Steps to reproduce

Use chrome://crash or similar to create a minidump without heap. Load it on various machines and run "lmv m kernel32". You can also use sigcheck to compare the version numbers of kernel32.dll on the machine and in the symbol server. Use dumpbin /headers to verify that the timestamp and image size match while the version number varies.

### Expected Behavior

It is crucial that the symbol server triplet uniquely identify a particular file. Identifying a file which is "the same except for the version number" is not actually corret.

### Actual Behavior

Microsoft's deterministic build system seems to be publishing files that are not identical (version number has changed) but overwrite each other in the symbol server. Nope. That's not good.

**Comment by randomascii** [comment] 2022-01-02 19:47
I've put the relevant files (three copies of kernel32.dll and a crash dump that will happily refer to any one of them) in this shared Google drive folder:
https://drive.google.com/drive/folders/1EUGs6iNqNXvWb98KMYcSBbXzIXUWGoWw

**Comment by zooba** [comment] 2022-01-06 20:19
Thanks, I'm seeing if I can chase down someone who may know what's going on here. This seems bad, though there may be a legitimate reason for it.

I assume you've got the latest windbg available?

**Comment by randomascii** [comment] 2022-01-06 21:13
Yeah, I tried this with the latest windbg, but it won't matter because it's the timestamp/image-size/name triplet reuse that is the problem. I can reproduce the issue using RetrieveSymbols.exe (https://github.com/google/UIforETW/blob/main/bin/RetrieveSymbols.exe) but also I can see that I have three different files with the same timestamp/image-size/name triplet, and once that is true there is nothing that windbg or any other symbol-server client can do.

**Comment by randomascii** [comment] 2022-01-06 21:30
This has been reported as a problem in the past, such as here, where it causes (understandably) developer confusion:

https://github.com/m417z/winbindex/issues/139

**Comment by AvriMSFT** [comment] 2022-03-10 20:52
Hey @zooba! Any updates here?

**Comment by rhuijben** [comment] 2022-11-22 14:41
Any news half a year later? @AvriMSFT @zooba?

**Comment by zooba** [comment] 2022-11-30 20:49
The Windows build team acknowledged that they're doing it, but I don't know how much further it got than that. If it's still happening, probably didn't go anywhere. I'll see if the people I was in touch with are still on it.

**Comment by AdamBraden** [comment] 2023-11-13 16:34
Closing the loop here - this was resolved over the summer. Let us know if something is not working right.

**Closed as completed by AdamBraden** 2023-11-13 16:34 UTC
Labels: Status-Investigating, Needs-Triage :mag:

**Comment by randomascii** [comment] 2023-11-13 17:49
By "resolved" does this mean that files will not be overwritten anymore? As in, retrieving PE files from the symbol server should now retrieve the correct version? That would be great.

**Comment by m417z** [comment] 2023-11-14 16:42
It would indeed be interesting to see how it was resolved. I still see the same issue in recent files. For example:
wiatrace.dll: https://winbindex.m417z.com/?file=wiatrace.dll
Versions 10.0.19041.3570 and 10.0.19041.3636, x64 architecture.
The hashes are:
* [f13e3850767d8841ca9b1fb68aabcc195efff0ab9300d3e5ad68435a596092f7](https://www.virustotal.com/gui/file/f13e3850767d8841ca9b1fb68aabcc195efff0ab9300d3e5ad68435a596092f7/details)
* [c52a5424d7a109d73739e20e71fa58744de6bb19ff1357f36e07505dd2e90ca6](https://www.virustotal.com/gui/file/c52a5424d7a109d73739e20e71fa58744de6bb19ff1357f36e07505dd2e90ca6/details)

Both files have the same timestamp and image size, so the link for both files is:
https://msdl.microsoft.com/download/symbols/wiatrace.dll/00EA0FC7a000/wiatrace.dll

The files were published in October 10 and 26, respectively, so after "this summer", I assume.

**Comment by zooba** [comment] 2023-12-06 17:12
It's been resolved, but only in the current branch (at the time, a few months ago). So build 19041 (Windows 10 April 2020 update) is not going to have the correction, but newer builds should be fine. I understand the issue is inherently part of the build process, rather than the server implementation.

**Comment by m417z** [comment] 2024-03-12 10:01
Here's another example:
wiatrace.dll: https://winbindex.m417z.com/?arch=insider&file=wiatrace.dll
Versions 10.0.23619.1000 and 10.0.23620.1000, x64 architecture.
The hashes are:
* [4541a5506fb6b82becaf9fcb00ede0261305a018bcf1f218e5819246c341bbc2](https://winbindex.m417z.com/?arch=insider&file=wiatrace.dll&search=10.0.23619.1000+x64)
* [a493b3d2efe6a98c00ec191cd0f53226c52bb8dc050b9b345a4db2a6738665d0](https://winbindex.m417z.com/?arch=insider&file=wiatrace.dll&search=10.0.23620.1000+x64)

Both files have the same timestamp and image size, so the link for both files is:
https://msdl.microsoft.com/download/symbols/wiatrace.dll/C5004E2Ba000/wiatrace.dll

The files were published in January 18 and 25, 2024, respectively. How new should they be to have the fix? I'm also curious how the fix was implemented, any details about that?

**Comment by zooba** [comment] 2024-03-18 22:13
I don't have the exact number, but I believe the fix is somewhere during the `10.0.25???.?` version numbers, so anything before that is likely to keep showing it (as the fix is not in those branches), while newer builds should have updated timestamps to match the changed version number.
