### ISSUE TITLE
Jump List entries no longer working after recent Windows 10 cumulative update (KB4592438)

### ISSUE THREAD

**Issue by Felix-Dev** [microsoft/WinDev#70] opened 2020-12-09 17:47 UTC
## Environment

| Item | Value | 
|---|---|
| OS, Version / Build |  Win32NT 10.0.19042.0 Microsoft Windows NT 10.0.19042.0 |
| Processor Architecture | AMD64 | 
| Processor Type & Model | Intel i7-8750H | 
| Memory | 16 GB |
| Storage Type, free / capacity (e.g. C: SSD 128GB / 512GB) | C: 73GB / 256GB | 
| Relevant apps installed  | Visual Studio, Firefox, Edge, VLC media player, Windows Terminal,... |

## Description
Yesterday, Windows Update installed, unrequested by me, the new cumulative Windows update `KB4592438` for Windows 10 20H2 systems on my device (link to update [here](https://support.microsoft.com/en-us/help/4592438/windows-10-update-kb4592438)). Since then, all my Jump List entries are broken:

![image](https://user-images.githubusercontent.com/1398851/101663791-67997300-3a4b-11eb-9064-9890c9d4b462.png)
(Visual Studio Jump List error even though the file in question is still in the correct file location)

![image](https://user-images.githubusercontent.com/1398851/101663967-957eb780-3a4b-11eb-9920-d92546b645e8.png)
(Microsoft Edge Dev Jump List)

![image](https://user-images.githubusercontent.com/1398851/101664050-afb89580-3a4b-11eb-97e4-5e2453873a3e.png)
(Windows Terminal App Jump List)

I have already tried the following to fix this bug without success:
* Restarting Windows (the classic way of fixing Windows errors)
* Uninstalling update KB4592438: Windows build changed back to `19042.630` but I am still seeing the exact same error
* Deleted Jump List entries and created them again 
* Turning Jump Lists on and off in Windows Settings
* Started Windows in safe mode

There are [more suggestions](https://superuser.com/questions/1321248/broken-jump-lists-on-windows-10) how to try fix broken Jump Lists but they sound increasingly desperate to me and also don't seem to work according to the author.

All Jump List entries were working fine on my previous Windows 10 20H2 build (19042.630). The [known issues](https://support.microsoft.com/en-us/help/4592438/windows-10-update-kb4592438) for this update make no mention of a Jump List bug.

As a frequent user of the Windows Jump Lists for all kinds of apps (VS, browser, music players,...) it goes without saying **that this bug has a major impact on my daily Windows productivity.**

## Steps to reproduce
For now, presumably install the Windows 10 `KB4592438` cumulative update and see if it reproduces on the test system. It could be that VS with workloads (like the `.NET desktop development` workload) has to be installed on the system at the time of the update.

Edit: As reported below, I recently did a clean install of Windows 10 running 19042.685 and then installed VS (no workload yet). Jump lists still worked fine. I then proceeded to install a VS workload - .NET desktop development - and my jump lists broke after the required restart. So at least on my setup it seems to be an issue of running Windows 10 19042.685 and then installing a VS workload.

## Expected behavior
Jump Lists should not break when updating Windows, especially when Windows 10 automatically installs updates on users' systems without prior consulting said user.

## Additional Context
When using the Event Viewer, I notice the following error is logged when clicking a Jump List entry:
![image](https://user-images.githubusercontent.com/1398851/101668837-5a7f8280-3a51-11eb-8644-1cd0b1779ce4.png)

## Links to the same/similar issue reported by others over time:
* https://superuser.com/questions/1321248/broken-jump-lists-on-windows-10
* https://answers.microsoft.com/en-us/windows/forum/windows_10-start-win_taskbar/windows-10-jump-lists-broken-by-recent-update/9deba8f4-ccd7-41eb-9943-0444cb256f20

**Comment by Felix-Dev** [comment] 2020-12-09 23:41
Update: I now used a system restore point to get back to the state before the update -- running 19042.630 now and Jump List entries are working again for me as they should. 

I have also paused updates on my system now in case update `KB4592438` really is faulty here for at least some devices.

**Comment by Felix-Dev** [comment] 2020-12-10 23:16
So, using a system restore point back to 19042.630, I am getting a whole bunch of other issues now - such as the emoji panel/Clipboard history panel, touch keyboard and the Snip & Sketch shell UI no longer being displayed. Previously, they were working fine though so something else broke as part of the system restore.

This is an even bigger deal-breaker for me so I am back to OS build19042.685 now. Meaning, again, no working Jump List entries. I really don't want to clean install Windows 10 again so I am hoping for some kind of fix (either being deployed as a Windows update or some working suggestion how to fix this on my current Windows build - 19042.685) @bitcrazed FYI

**Comment by Felix-Dev** [comment] 2020-12-14 20:35
Over the weekend, I did a clean install of my Windows because nothing worked to get my jumplists back without deploying some rather unhandy workaround. So, clean installed Windows 10 20H2 with update KB4592438 and everything was working as it should (inlcuding Jump Lists). Then I installed VS 2019 16.8.3 (just the base editor witout any workload) and everything still worked fine.

Until now...

I just installed the .NET desktop development workload: 
![image](https://user-images.githubusercontent.com/1398851/102131761-f8f55480-3e52-11eb-80c5-24276be4a864.png)

Restarted my PC and was greeted by this:
![image](https://user-images.githubusercontent.com/1398851/102131888-29d58980-3e53-11eb-9882-572dd660fb1a.png)

Apparently, I cannot install a VS workload - which is vital for me as a developer - without jump lists breaking on Windows 10 19042.685.

I have no faith in system restore (restoring to a point before the workload was installed) to fix this issue. In other words: I can again do a clean-install and either have to 
* force Windows to not shove update KB4592438 down my throat or 
* just not install VS and wait for someone at MS (either the VS team or the Windows team) to take a look at this issue and provide a proper fix.

This is borderline frustrating to say the least and entirely unacceptable. A VS workload installation appears to have broken Jump Lists. 

Btw, the workaround mentioned in the beginning? I basically have to manually start the `rundll32` process like such:
`%SystemRoot%\System32\rundll32.exe shell32.dll,SHCreateLocalServerRunDll {c82192ee-6cb5-4bc0-9ef0-fb818773790a}` typed into `Run` (Win + R). Automating this process did not work for me.

**Comment by just1a-person** [comment] 2020-12-16 14:06
@Felix-Dev Are you saying that this issue was caused by the update or the VS workload installation?

**Comment by Felix-Dev** [comment] 2020-12-16 20:38
@itsme-alan It seems to be a combination of both. Initially, on Friday last week, I had a working VS with all my required workloads (i.e. .NET desktop development) installed and correctly working jump lists. Then, Windows installed the new December cumulative update on my system (KB4592438 - build 19042.685) and my jump lists broke. Uninstalling that update via Windows Control Panel restored jump lists functionality again (but unfortunately broke other things).

Then two days ago I did a fresh install of Windows 10 on my system running the same latest 20H2 build - so 19042.685. Jump lists were working fine after the clean install. I then proceeded to install Visual Studio. First, I only installed VS itself (with no additional workloads) and my jump lists were still working fine. After that, I installed the `.NET desktop development` workload via the Visual Studio Installer and after the required restart, my jump lists were broken again.

So, in one case it was a Windows update (with VS already installed and set up with workloads) which broke my jump lists and in the other case it was installing VS with workloads on my system after a clean install of Windows. In both cases I had Windows 10 19042.685 running on my system. Thus, from what I can tell for now it seems to be a combination of both this specific Windows build and having VS (with workloads) installed.

**Comment by just1a-person** [comment] 2020-12-17 04:41
I am running the latest Insider Build 20277.1

VS 16.8 with these workloads:

- ASP.NET and web development
- .NET Desktop development
- Desktop development with C++
- Universal Windows Platform Development
- Linux Development with C++
- .NET cross-platform development

and jumplists works fine for me

Either it was fixed in the latest Insider builds or this bug must be a rare case

**Comment by Felix-Dev** [comment] 2020-12-17 12:34
@itsme-alan Yes, I suspect it is a rare case. Which is why I am quite a bit frustrated that I managed to get this issue two times in a row (especially after that clean install!). I suspect it is thus reproducible on my machine for whatever reason (though I might also give it yet another clean install try).

Ultimately, I would like for someone (presumably at MS) to supply me with a list of steps to *fix* this issue on my device so that if it does happen, jump lists  can be made working again. There is a workaround available though due to my setup, that one is not really feasible in the mid- to long-term.

**Comment by just1a-person** [comment] 2021-01-03 15:33
No one has responded to this? It's been a while. (They might on holiday)

@Felix-Dev Do you still have this issue?

**Comment by Felix-Dev** [comment] 2021-01-04 16:40
@itsme-alan Yes, they most definitely were/are on holiday.

Some good news for now. I managed to install Visual Studio 2019 again on a fresh Windows 10 19042.685 install (with KB4592438 included) with all three workloads I require -- without breaking my jump lists in the process. 

No clue if that makes a difference but this time I installed the workloads in this order:
* Desktop development with C++
* Universal Windows Platform development
* .NET desktop development

Previously, I first installed the .NET desktop development workload and that killed my jump lists.

Why I now made full system backups as well (since restore points are seemingly unable to repair broken jump lists), I am kinda paranoid by now checking my jump lists after every installation - no matter if it's an OS update or an app installation (they are that vital to me on Windows). As written earlier, I would still like for the Windows team to provide a set of steps how broken jump lists ca be fixed (without requiring a full system backup restore or clean installation). I (or others) might face this issue again in the future so a feasible jump list repair guide would be well appreciated by me. As such, I am not yet closing this issue.

**Comment by zooba** [comment] 2021-01-04 21:57
Apologies for the lack of response, we have indeed mostly been out for breaks. I'll also mention that this repository isn't meant to be a replacement for reporting issues through Feedback Hub, particularly in cases like this where something is obviously broken by accident, rather than by design (that tool does a better job of collecting additional logs, aggregating common reports, and assigning to the correct team). We're also trying to keep a focus on developer-specific issues, as those are the ones that our team is focused on. The best we can do with reports like this is essentially to put them into Feedback Hub for you (and in some cases make sure the right engineer gets to read it, but that can't be relied upon).

In this case, I'm afraid I totally can't help. But there are some other people watching this repo who are closer to the relevant team and might be able to pass it along. I just didn't want to leave you without a response for any longer.

**Comment by ericsampson** [comment] 2021-01-24 17:31
If the feedback hub is the right place, probably better to move this there (with a link to here?) and close this issue so people don't think it's being tracked/worked here. Cheers!

**Comment by AvriMSFT** [comment] 2021-04-14 16:53
@Felix-Dev Sorry for the delayed response. @zooba and the rest, thank you for replying and helping out on this issue. Unfortunately, this issue is out of scope for the repo. The best thing to do would be to author a piece of feedback in the Feedback Hub and include the link here. I (and perhaps others on this thread) can then upvote the feedback so that it gets more attention. Once you've done that, I'll close out the issue here. I recommend filing under Desktop Environment -> Taskbar

**Comment by Eli-Black-Work** [comment] 2021-06-23 02:33
Has anyone reported this to Feedback Hub?

**Closed as completed** 2021-06-30 13:01 UTC
Labels: Needs-Author-Feedback, Status-No Recent Activity, Status-FeedbackHubFollowUp
