### ISSUE TITLE
Windows wakes up randomly and predictably and I don't know why

### ISSUE THREAD

**Issue by timheuer** [microsoft/WinDev#42] opened 2020-09-30 16:14 UTC
As a Windows dev I keep my workstation 'on' all times.  My power configurations are set to 'power mode (plugged in)' and each day after work my machine screen 'sleeps' -- but at predictably 10PM each night something is waking it up, camera turning on for Hello auth and then goes back to sleep.  It apparently happens as well around 3AM.  It is unclear to me what is waking this up.  I understand there could be many, but I'm not expecting idle time to fully wake my machine.

**Comment by orcmid** [comment] 2020-10-01 18:52
I have a Windows XP Tablet PC that is always on and, when I once slept nearby, I would awaken to this behavior in the middle of the night.  I don't know if it still does that and I am not going to stay awake long enough to find out.  There is no camera so I can't observe about that.

The three other PCs around the house, all running W10 and equipped with cameras, are shut down at night, so whatever it is, it is not happening.

I wonder if this is related to a middle of the night update window and/or some sort of wake-on-LAN behavior.

**Comment by ArthurBrussee** [comment] 2020-10-12 21:57
Same here! I've somewhat given up on hibernating my desktop PC as it reliably will be on the next day.

To add to it - laptops have the same behaviour. I have nearly fried my Razer Blade multiple times because it woke up in my bag overnight creating its own personal sauna.

Googling around shows a variety of reasons / workaround from people, some more effective than others. I've not had issues with MBPs doing this, certainly worth fixing!

**Comment by warpdesign** [comment] 2020-11-27 07:52
Not sure it's related but my Surface Book also does not enter deep sleep sometimes. And it appears to be related to the SDCard: if I remove the SDCard, the problem is gone.

**Comment by nmoinvaz** [comment] 2020-11-27 17:35
It might be helpful if there was a way to determine what applications are resetting the system idle timer - or if this information was logged in the Event Viewer in such a way that it wasn't spamming it or displayed in real-time in Task Manager.

**Comment by zakius** [comment] 2021-01-04 18:04
been experiencing wake-ups (that often stayed on) at 3-6AM every time I had wake up controlled by OS set up *for years*, on different machines and windows versions, with auto updates both on and off

though I rarely put my machine to sleep, pretty much every time I did with OS wake up enabled it happened

can't provide much more details and the direct reason of that may be different but it may be helpful too

**Comment by rafalfitt** [comment] 2021-01-10 19:39
hint:
C:\Windows\System32\powercfg.exe -lastwake

**Comment by AvriMSFT** [comment] 2021-04-13 18:58
Unfortunately, this issue is out of scope for this repo, so it won't be tracked here. BUT the team responsible for this issue gets feedback and bug reports via Feedback Hub! Please file this issue in the Feedback Hub under "Power and Battery". Once you've done this, please paste the link here and I can go ahead and give the feedback an upvote. In the meantime, I'll track down an owner for this issue and make them aware.

**Comment by Eli-Black-Work** [comment] 2021-06-23 02:28
@timheuer, What do you see when you run `powercfg /waketimers` from an elevated command prompt?

**Closed as completed** 2021-06-30 13:01 UTC
Labels: Status-Investigating, Needs-Author-Feedback, Area-Sleep, Status-No Recent Activity, Status-FeedbackHubFollowUp
